### ISSUE TITLE
Does support sdxl？

### ISSUE THREAD

**Issue by RyanHuangNLP** [magic-research/piecewise-rectified-flow#2]
This method support sdxl？and what is the training data format?
'''
make_train_dataset = None
    if make_train_dataset is None:
        raise NotImplementedError("Please implement `make_train_dataset` function.")
'''
would you like to provide a data sample?

**Comment by appleyang123** [comment]
yes, i am using sdxl inpainting model to do some background generation experiments. This method can support sdxl?

**Comment by HanshuYAN** [comment]
Hi, SDXL is supported now!
