### ISSUE TITLE
About perflow training

### ISSUE THREAD

**Issue by noway2beatme** [magic-research/piecewise-rectified-flow#6]
I would like to express my admiration for your impressive work and the innovative approach you have taken in your project. Having gone through the README, I noticed that you mentioned the model fine-tuning only required 4000 steps to converge, which is quite remarkable. This piqued my curiosity, and I was hoping you could clarify: Is the EMA model specifically, or the original model, that requires only 4000 steps to converge?

**Comment by HanshuYAN** [comment]
Thanks. We enable the EMA during training.
