### ISSUE TITLE
The dataset of PeRFlow-SDXL-DreamShaper

### ISSUE THREAD

**Issue by KenRanmzes** [magic-research/piecewise-rectified-flow#9]
How could you get the dataset to finetune Dreamshaper?

**Comment by HanshuYAN** [comment]
PeRFlow uses LAION for SDXL-base acceleration. After training, we obtain the perflow-delta-weights.   Then, we merge the delta-weights into SDXL-dreamshaper, which is the released PeRFlow-SDXL-DreamShaper.
